### ISSUE TITLE
Action failed to run

### ISSUE THREAD

**Issue by BILY5354** [simonecorsi/mawesome#166]
Hello, after I configured it according to the process, the execution failed in action. The error prompt is as follows. Which step is the problem? thank you.
![image](https://user-images.githubusercontent.com/46767838/182351572-9d811278-03c9-4864-8377-48efbfda747a.png)

**Comment by simonecorsi** [comment]
Hi! 👋 

I've seen your repo and it seems to me that you managed to get it to work, are you still having the problem?

Did you have to do some extra steps that I didn't mention in the README to make it work? Please let me know so I can update it :)

**Comment by BILY5354** [comment]
Hi! 
First, I copied your action code ```.yml``` like this. But didn't work.   
```
name: Update awesome list

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Awesome generator
        uses: simonecorsi/mawesome@latest
        with:
          api-token: ${{ secrets.API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          github-name: ${{ github.repository_owner }}
```  
Then, I replaced it like this. The code I found in the [awesome-stars-eryajf](https://github.com/eryajf/awesome-stars-eryajf) repository. Now, it works but I don't know what the problem is.  
```
name: Update awesome list

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Awesome generator
        uses: simonecorsi/mawesome@v2
        with:
          api-token: ${{ secrets.ACCESS_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          template-path: "template/README.ejs"
          github-name: ${{ github.repository_owner }}
```

**Comment by simonecorsi** [comment]
mmm 🤔 

`template-path` is optional if you want to use your own template, is possible that the secret with the github token was missing and/or with a different name or malformed for some copy/paste? Just trying to understand because it's the first time someone have this problem and I don't know what to look for!

**Comment by BILY5354** [comment]
This is my step to run your action.

1. Create a new repo.
2. Generate the api then copy in the repo like this. ![image](https://user-images.githubusercontent.com/46767838/182876771-5c0b34f4-7da9-459f-b14c-1a66657bbb4d.png)
3. Create the file directory ```[.github/workflows```and add  ```main.yml``` file. The file code is copyed your file.   
```
name: Update awesome list

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Awesome generator
        uses: simonecorsi/mawesome@latest
        with:
          api-token: ${{ secrets.API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          github-name: ${{ github.repository_owner }} 
```   
4. Created ```template``` directory and add ```README.ejs``` file. Also copy your file.  
5. At last, create ```README.md``` and run action but failed.

So I replaced part of the code as I said before, and it works. But I'm not sure what went wrong. I hope my description is helpful.  Thanks.
